export {default as Menu} from './menu/Menu.jsx'
export {default as Booknow} from './booknow/Booknow.jsx'
export {default as Beesafe} from './beesafe/Beesafe.jsx'
export {default as Aboutus} from './aboutus/Aboutus.jsx'
export {default as Contactus} from './contactus/Contactus.jsx'
export {default as Storelocations} from './storelocations/Storelocations.jsx'
